function(vdb_enable_sanitizers target)
  if(MSVC)
    return()
  endif()
  if(VDB_ENABLE_ASAN)
    target_compile_options(${target} PRIVATE -O1 -fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE -fsanitize=address,undefined)
  elseif(VDB_ENABLE_TSAN)
    target_compile_options(${target} PRIVATE -O1 -fsanitize=thread -fno-sanitize-recover=all -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE -fsanitize=thread)
  elseif(VDB_ENABLE_SANITIZERS)
    # macOS 26's current arm64 ASan runtime can spin during dyld allocator
    # initialization before main. Keep the Apple gate useful with UBSan; run
    # ASan in Linux CI, where the shadow-memory runtime is stable.
    if(APPLE)
      target_compile_options(${target} PRIVATE -O1 -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer)
      target_link_options(${target} PRIVATE -fsanitize=undefined)
    else()
      target_compile_options(${target} PRIVATE -O1 -fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer)
      target_link_options(${target} PRIVATE -fsanitize=address,undefined)
    endif()
  endif()
endfunction()
